export const PUBLIC_BLOB_HOST: string;
export const RUNTIME_MANIFEST_BLOB_PATHNAME: string;
export const RUNTIME_MANIFEST_BLOB_URL: string;
export const RUNTIME_CATALOG_RELEASE_INDEX_PATHNAME: string;
export const RUNTIME_CATALOG_RELEASE_INDEX_BLOB_URL: string;
export const LOCAL_RUNTIME_MANIFEST_PUBLIC_PATH: string;
export const LOCAL_RUNTIME_MANIFEST_RELATIVE_PATH: string;
